version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
    env_file:
      - .env
    volumes:
    - esdata:/usr/share/elasticsearch/data

volumes:
  esdata: